# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php
sudo: false

php:
  - 5.3

env:
  - DB=MYSQL CORE_RELEASE=3.2

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.5
      env: DB=SQLITE CORE_RELEASE=3.2
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2 COVERAGE=1
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.2 COVERAGE=2
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2 COVERAGE=3
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.3
  allow_failures:
    - env: DB=PGSQL CORE_RELEASE=master


before_script:
 - composer self-update
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - phpunit shop-lite/tests/
